version: '3.8'

services:
  ganache:
    image: trufflesuite/ganache:latest
    ports:
      - "8545:8545"
    volumes:
      - ganache_data:/ganache/data
    command:
      - --chain.chainId=1337
      - --wallet.totalAccounts=10
      - --wallet.defaultBalance=1000000
      - --server.host=0.0.0.0
      - --wallet.deterministic=true
      - --database.dbPath=/ganache/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8545"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

volumes:
  ganache_data: 