const hre = require("hardhat");
const fs = require('fs');

async function main() {
  // Always use the same account (first account from deterministic Ganache)
  const [deployer] = await ethers.getSigners();
  console.log("Deploying contracts with account:", deployer.address);

  // Force nonce to 0 to get same address
  const nonce = await ethers.provider.getTransactionCount(deployer.address);
  if (nonce !== 0) {
    console.error("Warning: Deployer account nonce is not 0. Contract address will be different!");
    console.error("To fix this, restart Ganache using: docker-compose down -v && docker-compose up -d");
    process.exit(1);
  }

  // Deploy contract
  const YourContract = await ethers.getContractFactory("YourContract");
  const contract = await YourContract.deploy();
  await contract.waitForDeployment();

  const contractAddress = await contract.getAddress();
  console.log("Contract deployed to:", contractAddress);

  // Expected address (will be the same every time with nonce 0)
  const EXPECTED_ADDRESS = "0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9";
  
  if (contractAddress !== EXPECTED_ADDRESS) {
    console.warn("Warning: Contract address is different from expected!");
    console.warn(`Expected: ${EXPECTED_ADDRESS}`);
    console.warn(`Actual: ${contractAddress}`);
  }

  // Update .env files
  const envContent = `
# Generated by deploy script - DO NOT MODIFY MANUALLY
PRIVATE_KEY=60edc3236511017a6aba96f7c1fab68c9c419ac2673c90349e4de5fa78330759
VITE_CONTRACT_ADDRESS=${contractAddress}
VITE_NETWORK_ID=1337
VITE_NETWORK_NAME=Ganache
`;

  // Write to both .env and .env.local
  fs.writeFileSync('.env', envContent);
  fs.writeFileSync('.env.local', envContent);
  
  console.log("\nEnvironment files updated!");
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(error);
    process.exit(1);
  }); 