name: Notify Telegram on PR or Merge

on:
  pull_request:
    types: [opened]
  push:
    branches:
      - main

jobs:
  notify-telegram:
    runs-on: ubuntu-latest
    steps:
    - name: Send Telegram Notification
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        if [[ "${{ github.event_name }}" == "pull_request" ]]; then
          curl -s -X POST https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage \
          -d chat_id=$TELEGRAM_CHAT_ID \
          -d text="🛠️ A new Pull Request is opened: ${{ github.event.pull_request.html_url }} by ${{ github.event.pull_request.user.login }}";
        elif [[ "${{ github.event_name }}" == "push" ]]; then
          curl -s -X POST https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage \
          -d chat_id=$TELEGRAM_CHAT_ID \
          -d text="✅ A branch was merged into main: ${{ github.event.head_commit.message }} by ${{ github.actor }}";
        fi
